os: windows

language: node_js

node_js:
  - "12"

before_install:
  - npm install -g yarn

install:
  - cd frontend
  - yarn
  - cd ../app
  - ./win_install.bat

script:
  - cd frontend
  - yarn run dist
  - cd ../app
  - ./win_build.bat
