name: Release

on:
  push:
    tags: v*

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
        - os: macos-latest
          platform: 'mac'
        - os: windows-latest
          platform: 'win'
        - os: ubuntu-latest
          platform: 'linux'
    runs-on: ${{ matrix.os }}
    env:
      npm_config_target: 9.3.1
      npm_config_runtime: "electron"
      APPLEID: ${{ secrets.APPLEID }}
      APPLEIDPASS: ${{ secrets.APPLEIDPASS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: Install
        run: |
          yarn
          yarn run download-pandoc
          cd frontend
          yarn
          cd ..

      - name: Build
        run: |
          cd frontend
          yarn run build
          cd ..
          yarn run build
          yarn run electron-builder --${{ matrix.platform }} -p never

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            out/Yank-Note*.*
            out/latest*.yml
