# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    tags: v*

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.3

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x
      
      - name: Install
        run: |
          npm install -g yarn
          ./win-install.bat
          cd frontend
          yarn
          cd ..
          
      - name: Build
        run: |
          cd frontend
          yarn run build
          cd ..
          ./win-build.bat

      - name: GH Release
        uses: softprops/action-gh-release@v0.1.5
        with:
          files: |
            out/Yank-Note*.*
            out/latest*.yml

